import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/NavBar";
import Footer from "../components/footer/Footer";
import SideBar from "@/components/SideBar";
import Hero from "@/components/Hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, hasHero = false }) {
    return (
        <html lang="en" className="">
            <body className={inter.className}>
                <div className="w-full min-h-screen bg-slate-100">
                    <Navbar />
                    <Hero />
                    <div className="flex flex-row px-8 my-12 justify-evenly">
                        <section className="w-2/3">{children}</section>
                        <div className="w-2/7">
                            <SideBar />
                        </div>
                    </div>

                    <Footer />
                </div>
            </body>
        </html>
    );
}
